/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.NhaxuatbanDAO;
import DTO.NhaXuatBan;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anh Tu
 */
public class Form_NhaXuatBan extends javax.swing.JFrame {

    DefaultTableModel modelNhaXuatBan;

    /**
     * Creates new form Form_TacGia
     */
    
     
    /**
     * Creates new form Form_NhaXuatBan
     */
    public Form_NhaXuatBan() throws Exception {
        initComponents();
        this.setTitle("FormNhaxuatban");
        this.setLocation(80, 40);
        modelNhaXuatBan= (DefaultTableModel) tblNhaxuatban.getModel();
        Load();
    }
    
    public void Load() throws Exception{
        NhaxuatbanDAO.HienThi();
        HienNhaxuatban(NhaxuatbanDAO.List);
        
    }
public void HienNhaxuatban(ArrayList<NhaXuatBan> Listx) {
        modelNhaXuatBan.setRowCount(0);
        Listx.forEach((x) -> {
            modelNhaXuatBan.addRow(new Object[]{
                x.getMaNhaXuatBan(), x.getTenNhaXuatBan()
            });
           
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtManhaxb = new javax.swing.JTextField();
        txtTenNhaxb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhaxuatban = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setText("Thông Tin Nhà Xuất Bản");

        jLabel2.setText("Mã nhà xuất bản");

        jLabel3.setText("Tên nhà xuất bản");

        tblNhaxuatban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã tác giả", "Tên tác giả"
            }
        ));
        tblNhaxuatban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhaxuatbanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhaxuatban);

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Cập nhật");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 102));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(33, 33, 33)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtManhaxb, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNhaxb, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtManhaxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNhaxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thoát ko ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
           
            try {
                 AdminForm x;
                x = new AdminForm();
                  x.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(TKsoluong.class.getName()).log(Level.SEVERE, null, ex);
            }
          
            dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

   private static String generateNextCode(DefaultTableModel model) {
    // Tạo danh sách chứa tất cả các mã hiện có trong bảng
    ArrayList<String> existingCodes = new ArrayList<>();
    int rowCount = model.getRowCount();
    for (int i = 0; i < rowCount; i++) {
        String codeValue = (String) model.getValueAt(i, 0);
        
        // Sử dụng biểu thức chính quy để kiểm tra xem giá trị có phải số nguyên hay không
        if (codeValue.matches("\\d+")) {
            existingCodes.add(codeValue);
        }
    }

    // Tìm mã lớn nhất trong danh sách mã hiện có
    String maxCode = "";
    for (String code : existingCodes) {
        if (code.compareTo(maxCode) > 0) {
            maxCode = code;
        }
    }

    // Tạo mã mới bằng cách tăng mã lớn nhất lên 1 và định dạng nó thành chuỗi
    int nextCodeNumber = Integer.parseInt(maxCode) + 1;
    return String.valueOf(nextCodeNumber);
}


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                                            
    // TODO add your handling code here:
                                       
    // TODO add your handling code here:
    if (txtManhaxb.getText().isEmpty()|| txtTenNhaxb.getText().isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin");
    } else {
       NhaXuatBan tl = new NhaXuatBan();
            ThemNhaXuatban(tl);

            try {
                NhaxuatbanDAO.ThemNhaXuatBan(tl);
            } catch (Exception ex) {
                // Xử lý lỗi khi thêm vào cơ sở dữ liệu
                ex.printStackTrace();
            }

            try {
                Load();
            } catch (Exception ex) {
                // Xử lý lỗi khi tải dữ liệu
                ex.printStackTrace();
            }
        
    
    
    

}

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
            XoaNhaXuatban();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblNhaxuatbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaxuatbanMouseClicked
        // TODO add your handling code here:
         int index = tblNhaxuatban.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng");
        } else {
            txtManhaxb.setText(NhaxuatbanDAO.List.get(index).getMaNhaXuatBan());
            txtTenNhaxb.setText(NhaxuatbanDAO.List.get(index).getTenNhaXuatBan());
        
    }            
    }//GEN-LAST:event_tblNhaxuatbanMouseClicked
public void XoaNhaXuatban() throws SQLException, Exception {
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            int index = tblNhaxuatban.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng để xóa");
            } else {
                
                    NhaxuatbanDAO.XoaNhaXuatBan(txtManhaxb.getText());
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                    NhaxuatbanDAO.HienThi();
                    HienNhaxuatban(NhaxuatbanDAO.List);
                

            }
        }

    }
 public void ThemNhaXuatban(NhaXuatBan tl) {
         tl.setMaNhaXuatBan(txtManhaxb.getText());
         tl.setTenNhaXuatBan(txtTenNhaxb.getText());
        
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_NhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_NhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_NhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_NhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Form_NhaXuatBan().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Form_NhaXuatBan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhaxuatban;
    private javax.swing.JTextField txtManhaxb;
    private javax.swing.JTextField txtTenNhaxb;
    // End of variables declaration//GEN-END:variables
}
