/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.BanDocController;
import DAO.PhieuController;
import DAO.XuLyQuanHanController;
import DTO.BanDoc;
import DTO.Phieu;
import DTO.XuLyQuaHan;
import static GUI.AdminForm.ListMaP;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;

/**
 *
 * @author admin
 */
public class NhanVienQLMuonTraForm extends javax.swing.JFrame {

    /**
     * Creates new form NhanVienQLMuonTra
     */
    DefaultTableModel modelXuLy;
    DefaultTableModel modelPhieu;
    DefaultTableModel TimKiem;

    public NhanVienQLMuonTraForm() throws Exception {
        this.setTitle("Quản lý mượn trả");
        initComponents();
        TimKiem = (DefaultTableModel) tbl_TimKiem.getModel();
        modelXuLy = (DefaultTableModel) tblQuaHan_QLQH.getModel();
        modelPhieu = (DefaultTableModel) tblQuanLyMuonTra.getModel();
        Load();
        HTcbx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelQuanLyPhieuMuon = new javax.swing.JPanel();
        txtNgayTra_QLMT = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtMaPhieu_QLMT = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNgayMuon_QLMT = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtNgayThucTra_QLMT = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMaSinhVien_QLMT = new javax.swing.JTextField();
        txtHoVaTen_QLMT = new javax.swing.JTextField();
        btnLapPhieuMuon = new javax.swing.JButton();
        btnSuaPhieuMuon = new javax.swing.JButton();
        btnXoaPhieuMuon = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblQuanLyMuonTra = new javax.swing.JTable();
        btnDangXuat4 = new javax.swing.JButton();
        btnHienThiPhieuMuon = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        btnQuaHan = new javax.swing.JButton();
        cbxMaTL_NVQLMT = new javax.swing.JComboBox<>();
        jPanelQuanLyBanDoc = new javax.swing.JPanel();
        btnThemPhieuXL = new javax.swing.JButton();
        btnSuaPhieuXL = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMaXuLy_XLQH = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTienPhat_XLQH = new javax.swing.JTextField();
        btnDangXuat3 = new javax.swing.JButton();
        btnHienThiPhieuXL = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        cbxLyDo_XLQH = new javax.swing.JComboBox<>();
        cbxTrangThai_QLQH = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuaHan_QLQH = new javax.swing.JTable();
        cbxMaP = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        cbxDoiTuong = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        cbxThuocTinh = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_TimKiem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanelQuanLyPhieuMuon.setBackground(new java.awt.Color(245, 245, 245));

        txtNgayTra_QLMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayTra_QLMTActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Mã tài liệu");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("Mã phiếu");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Ngày mượn");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("Ngày thực trả");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("Mã sinh viên");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setText("Họ và tên");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("Ngày trả");

        txtMaSinhVien_QLMT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaSinhVien_QLMTFocusLost(evt);
            }
        });

        txtHoVaTen_QLMT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoVaTen_QLMTFocusGained(evt);
            }
        });

        btnLapPhieuMuon.setBackground(new java.awt.Color(0, 153, 102));
        btnLapPhieuMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLapPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        btnLapPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132335_add_icon.png"))); // NOI18N
        btnLapPhieuMuon.setText("Thêm  phiếu mượn");
        btnLapPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPhieuMuonActionPerformed(evt);
            }
        });

        btnSuaPhieuMuon.setBackground(new java.awt.Color(0, 153, 102));
        btnSuaPhieuMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132187_refresh_icon.png"))); // NOI18N
        btnSuaPhieuMuon.setText("Sửa phiếu mượn");
        btnSuaPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPhieuMuonActionPerformed(evt);
            }
        });

        btnXoaPhieuMuon.setBackground(new java.awt.Color(0, 153, 102));
        btnXoaPhieuMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132192_delete_icon.png"))); // NOI18N
        btnXoaPhieuMuon.setText("Xóa phiếu mượn");
        btnXoaPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPhieuMuonActionPerformed(evt);
            }
        });

        tblQuanLyMuonTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu", "Mã tài liệu", "Mã sinh viên", "Họ và tên", "Ngày mượn", "Ngày trả", "Ngày thực trả"
            }
        ));
        tblQuanLyMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyMuonTraMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblQuanLyMuonTra);

        btnDangXuat4.setBackground(new java.awt.Color(0, 153, 102));
        btnDangXuat4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangXuat4.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/171495_right_exit_icon (1).png"))); // NOI18N
        btnDangXuat4.setText("Đăng xuất");
        btnDangXuat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuat4ActionPerformed(evt);
            }
        });

        btnHienThiPhieuMuon.setBackground(new java.awt.Color(0, 153, 102));
        btnHienThiPhieuMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHienThiPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        btnHienThiPhieuMuon.setText("Hiển thị");
        btnHienThiPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiPhieuMuonActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 153, 102));
        jLabel38.setText(" Danh sách phiếu mượn ");

        btnQuaHan.setBackground(new java.awt.Color(0, 153, 102));
        btnQuaHan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuaHan.setForeground(new java.awt.Color(255, 255, 255));
        btnQuaHan.setText("Quá Hạn");
        btnQuaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaHanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQuanLyPhieuMuonLayout = new javax.swing.GroupLayout(jPanelQuanLyPhieuMuon);
        jPanelQuanLyPhieuMuon.setLayout(jPanelQuanLyPhieuMuonLayout);
        jPanelQuanLyPhieuMuonLayout.setHorizontalGroup(
            jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDangXuat4))
                    .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                        .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                                .addComponent(btnLapPhieuMuon)
                                .addGap(18, 18, 18)
                                .addComponent(btnSuaPhieuMuon)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaPhieuMuon))
                            .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                                .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(44, 44, 44)
                                .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaPhieu_QLMT)
                                    .addComponent(txtNgayMuon_QLMT)
                                    .addComponent(txtNgayThucTra_QLMT, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(cbxMaTL_NVQLMT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addGap(36, 36, 36)
                                .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHoVaTen_QLMT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(txtNgayTra_QLMT, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaSinhVien_QLMT)))
                            .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnHienThiPhieuMuon)
                                .addGap(472, 472, 472)
                                .addComponent(btnQuaHan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelQuanLyPhieuMuonLayout.setVerticalGroup(
            jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtMaSinhVien_QLMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtHoVaTen_QLMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayTra_QLMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtMaPhieu_QLMT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cbxMaTL_NVQLMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayMuon_QLMT)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtNgayThucTra_QLMT))))
                .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                        .addGroup(jPanelQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLapPhieuMuon)
                            .addComponent(btnSuaPhieuMuon)
                            .addComponent(btnXoaPhieuMuon)
                            .addComponent(btnHienThiPhieuMuon)
                            .addComponent(btnQuaHan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel38))
                    .addGroup(jPanelQuanLyPhieuMuonLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnDangXuat4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Quản lý phiếu mượn ", jPanelQuanLyPhieuMuon);

        btnThemPhieuXL.setBackground(new java.awt.Color(0, 153, 102));
        btnThemPhieuXL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemPhieuXL.setForeground(new java.awt.Color(255, 255, 255));
        btnThemPhieuXL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132335_add_icon.png"))); // NOI18N
        btnThemPhieuXL.setText("Thêm phiếu");
        btnThemPhieuXL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhieuXLActionPerformed(evt);
            }
        });

        btnSuaPhieuXL.setBackground(new java.awt.Color(0, 153, 102));
        btnSuaPhieuXL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaPhieuXL.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaPhieuXL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132187_refresh_icon.png"))); // NOI18N
        btnSuaPhieuXL.setText("Sửa phiếu");
        btnSuaPhieuXL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPhieuXLActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Mã phiếu mượn");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Mã xử lý");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Lý do");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("Tiền phạt");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Trạng thái");

        btnDangXuat3.setBackground(new java.awt.Color(0, 153, 102));
        btnDangXuat3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangXuat3.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/171495_right_exit_icon (1).png"))); // NOI18N
        btnDangXuat3.setText("Đăng xuất");
        btnDangXuat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuat3ActionPerformed(evt);
            }
        });

        btnHienThiPhieuXL.setBackground(new java.awt.Color(0, 153, 102));
        btnHienThiPhieuXL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHienThiPhieuXL.setForeground(new java.awt.Color(255, 255, 255));
        btnHienThiPhieuXL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/3671905_show_view_icon.png"))); // NOI18N
        btnHienThiPhieuXL.setText("Hiển thị");
        btnHienThiPhieuXL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiPhieuXLActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 153, 102));
        jLabel36.setText(" Danh sách xử lý quá hạn");

        cbxLyDo_XLQH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quá hạn", "Mất tài liệu", "Hỏng tài liệu" }));
        cbxLyDo_XLQH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLyDo_XLQHActionPerformed(evt);
            }
        });

        cbxTrangThai_QLQH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã nộp", "Chưa nộp" }));

        tblQuaHan_QLQH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã xử lý", "Mã phiếu", "Lý do", "Tiền phạt", "Trạng thái"
            }
        ));
        tblQuaHan_QLQH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuaHan_QLQHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuaHan_QLQH);

        javax.swing.GroupLayout jPanelQuanLyBanDocLayout = new javax.swing.GroupLayout(jPanelQuanLyBanDoc);
        jPanelQuanLyBanDoc.setLayout(jPanelQuanLyBanDocLayout);
        jPanelQuanLyBanDocLayout.setHorizontalGroup(
            jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyBanDocLayout.createSequentialGroup()
                .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuanLyBanDocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(btnThemPhieuXL))
                        .addGap(17, 17, 17)
                        .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQuanLyBanDocLayout.createSequentialGroup()
                                .addComponent(txtMaXuLy_XLQH, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(34, 34, 34)
                                .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTienPhat_XLQH, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxTrangThai_QLQH, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelQuanLyBanDocLayout.createSequentialGroup()
                                .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnSuaPhieuXL)
                                        .addComponent(cbxLyDo_XLQH, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxMaP, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelQuanLyBanDocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanelQuanLyBanDocLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQuanLyBanDocLayout.createSequentialGroup()
                                .addComponent(btnHienThiPhieuXL)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelQuanLyBanDocLayout.createSequentialGroup()
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                                .addComponent(btnDangXuat3)))))
                .addContainerGap())
        );
        jPanelQuanLyBanDocLayout.setVerticalGroup(
            jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyBanDocLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMaXuLy_XLQH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtTienPhat_XLQH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(cbxTrangThai_QLQH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbxLyDo_XLQH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemPhieuXL)
                    .addComponent(btnSuaPhieuXL)
                    .addComponent(btnHienThiPhieuXL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelQuanLyBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangXuat3)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Xử lý quá hạn", jPanelQuanLyBanDoc);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel41.setText("Nhập thông tin cần tìm");

        txtTimKiem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTimKiem.setText("Search");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
        });
        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimKiemMouseClicked(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        cbxDoiTuong.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbxDoiTuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phiếu", "Xử lý quá hạn", "Bạn đọc" }));
        cbxDoiTuong.setToolTipText("Chọn loại nhân viên ");
        cbxDoiTuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDoiTuongActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel42.setText("Chọn đối tượng cần tìm");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel43.setText("Chọn thuộc tính để tìm");

        cbxThuocTinh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbxThuocTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã đơn hàng", "Họ và tên", "Mã tài liệu" }));
        cbxThuocTinh.setToolTipText("Chọn kiểu tìm kiếm");

        btnTimKiem.setBackground(new java.awt.Color(0, 153, 102));
        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132289_search_icon.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm ");
        btnTimKiem.setToolTipText("Tìm kiếm hóa đơn");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tbl_TimKiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tbl_TimKiem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTimKiem)
                            .addComponent(cbxDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel43)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel43)
                    .addComponent(cbxThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(btnTimKiem))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tìm kiếm", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void HTcbx() {
        try {
            PhieuController.LayMaTL();
            PhieuController.LayMaP();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String s : PhieuController.ListMaTL) {
            cbxMaTL_NVQLMT.addItem(s);
        }

        for (String s : PhieuController.ListMaP) {
            cbxMaP.addItem(s);
        }
    }
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
         switch (cbxDoiTuong.getSelectedItem().toString()) {
            case "Phiếu":

                TimKiem.setColumnIdentifiers(new Object[]{
                    "Mã phiếu", "Mã tài liệu", "Mã sinh viên", "Họ và tên", "Ngày mượn", "Ngày trả", "Ngày thực trả"
                });
                switch (cbxThuocTinh.getSelectedItem().toString()) {
                    case "Mã Phiếu":
                        try {
                            PhieuController.TimMaPhieu(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;
                    case "Mã Sinh Viên":
                        try {
                            PhieuController.TimMaSV(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;
                    case "Tên Sinh Viên":
                        try {
                            PhieuController.TimTenSV(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;
                    case "Mã Tài liệu":
                        try {
                            PhieuController.TimMaTaiLieu(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;

                    default:
                        break;
                }

                HienThiPhieu1(PhieuController.List1);
                break;
            case "Xử lý quá hạn":

            TimKiem.setColumnIdentifiers(new Object[]{
                "Mã xử lý", "Mã phiếu", "Lý do", "Tiền phạt", "Trạng thái"
            });
            switch (cbxThuocTinh.getSelectedItem().toString()) {
                case "Mã xử lý":
                try {
                    XuLyQuanHanController.TimKiemMaXuLy(txtTimKiem.getText());
                } catch (Exception ex) {
                    Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
                case "Mã phiếu mượn":
                try {
                    XuLyQuanHanController.TimKiemMaPhieu(txtTimKiem.getText());
                } catch (Exception ex) {
                    Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;

                default:
                break;
            }

            HienThiXuLy1(XuLyQuanHanController.List1);
            break;
            case "Bạn đọc":

                TimKiem.setColumnIdentifiers(new Object[]{
                    "Mã bạn đọc", "Tên bạn đọc", "Ngày sinh", "Lớp - Khóa", "Số điện thoại" , "Giới tính"
                });
                switch (cbxThuocTinh.getSelectedItem().toString()) {
                    case "Mã bạn đọc":
                        try {
                            BanDocController.TimKiemMaSV(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;
                    case "Tên bạn đọc":
                        try {
                            BanDocController.TimKiemTenSV(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;

                    default:
                        break;
                }

                HienThiBanDoc1(BanDocController.List1);
                break;
                default:
                break;
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void cbxDoiTuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDoiTuongActionPerformed
         switch (cbxDoiTuong.getSelectedItem().toString()) {
            case "Phiếu":
                cbxThuocTinh.removeAllItems();
                cbxThuocTinh.addItem("Mã Phiếu");
                cbxThuocTinh.addItem("Mã Sinh Viên");
                cbxThuocTinh.addItem("Tên Sinh Viên");
                cbxThuocTinh.addItem("Mã Tài liệu");
                break;
            case "Xử lý quá hạn":
            cbxThuocTinh.removeAllItems();
            cbxThuocTinh.addItem("Mã xử lý");
            cbxThuocTinh.addItem("Mã phiếu mượn");
            break;
            case "Bạn đọc":
                cbxThuocTinh.removeAllItems();
                cbxThuocTinh.addItem("Mã bạn đọc");
                cbxThuocTinh.addItem("Tên bạn đọc");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbxDoiTuongActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemMouseClicked

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void btnHienThiPhieuXLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiPhieuXLActionPerformed

        try {
            BanDocController.HienThi();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        HienThiXuLy(XuLyQuanHanController.List);
    }//GEN-LAST:event_btnHienThiPhieuXLActionPerformed

    private void btnDangXuat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuat3ActionPerformed

        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn đăng xuất ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            HomePage x = new HomePage();
            x.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnDangXuat3ActionPerformed

    private void btnSuaPhieuXLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPhieuXLActionPerformed
        try {
            SuaXuLy();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaPhieuXLActionPerformed

    private void btnThemPhieuXLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhieuXLActionPerformed
        if (txtMaXuLy_XLQH.getText().trim().equals("")
                || txtTienPhat_XLQH.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin");
        } else {
            XuLyQuaHan tl = new XuLyQuaHan();
            try {
                ThemXuLy(tl);
            } catch (BadLocationException | ParseException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if (!XuLyQuanHanController.Check(txtMaXuLy_XLQH.getText())) {
                    try {
                        XuLyQuanHanController.Them(tl);
                    } catch (SQLException ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        XuLyQuanHanController.HienThi();
                        HienThiXuLy(XuLyQuanHanController.List);
                    } catch (Exception ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Đã tồn tại phiếu xử lý này này");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemPhieuXLActionPerformed

    private void btnHienThiPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiPhieuMuonActionPerformed

        try {
            PhieuController.HienThi();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        HienThiPhieu(PhieuController.List);
    }//GEN-LAST:event_btnHienThiPhieuMuonActionPerformed

    private void btnDangXuat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuat4ActionPerformed
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn đăng xuất ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            HomePage x = new HomePage();
            x.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnDangXuat4ActionPerformed

    private void tblQuanLyMuonTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyMuonTraMouseClicked
        int index = tblQuanLyMuonTra.getSelectedRow();
        if (index == -1) {
            //JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng");
        } else {
            txtMaPhieu_QLMT.setText(PhieuController.List.get(index).getMaPhieu());
            txtMaSinhVien_QLMT.setText(PhieuController.List.get(index).getMaBanDoc());
            cbxMaTL_NVQLMT.setSelectedItem(PhieuController.List.get(index).getMaTaiLieu());
            txtHoVaTen_QLMT.setText(PhieuController.List.get(index).getHoVaTen());
            txtNgayMuon_QLMT.setText(PhieuController.List.get(index).getNgayMuon() + "");
            txtNgayThucTra_QLMT.setText(PhieuController.List.get(index).getNgayThucTra() + "");
            txtNgayTra_QLMT.setText(PhieuController.List.get(index).getNgayTra() + "");

        }
    }//GEN-LAST:event_tblQuanLyMuonTraMouseClicked

    private void btnXoaPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPhieuMuonActionPerformed
        try {
            XoaPhieu();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaPhieuMuonActionPerformed

    private void btnSuaPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPhieuMuonActionPerformed
        try {
            SuaPhieu();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaPhieuMuonActionPerformed


    private void btnLapPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPhieuMuonActionPerformed
        if (txtMaPhieu_QLMT.getText().trim().equals("")
                || txtMaSinhVien_QLMT.getText().trim().equals("")
                || txtHoVaTen_QLMT.getText().trim().equals("")
                || txtNgayMuon_QLMT.getText().trim().equals("")
                || txtNgayTra_QLMT.getText().trim().equals("")
                || txtNgayThucTra_QLMT.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin");
        } else {
            Phieu tl = new Phieu();
            try {
                ThemPhieu(tl);
            } catch (BadLocationException | ParseException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if (!PhieuController.Check(txtMaPhieu_QLMT.getText())) // Kiểm tra tồn tại mã phiếu
                {
                    if (PhieuController.CheckKhoaNgoai(tl.getMaTaiLieu(), tl.getMaBanDoc())) { // Kiểm tra tồn tại mã TL,BD
                        try {
                            PhieuController.ThemPhieu(tl);

                        } catch (SQLException ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);

                        }
                        try {
                            PhieuController.HienThi();
                            HienThiPhieu(PhieuController.List);
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Mã bạn đọc hoặc mã tài liệu không tồn tại");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Phiếu này đã tồn tại");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnLapPhieuMuonActionPerformed

    private void txtNgayTra_QLMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayTra_QLMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayTra_QLMTActionPerformed

    private void btnQuaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaHanActionPerformed

        try {
            PhieuController.HTQuaHan();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        HienThiPhieu(PhieuController.List);
    }//GEN-LAST:event_btnQuaHanActionPerformed

    private void tblQuaHan_QLQHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuaHan_QLQHMouseClicked
        int index = tblQuaHan_QLQH.getSelectedRow();
        if (index == -1) {
            //JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng");
        } else {
            txtMaXuLy_XLQH.setText(XuLyQuanHanController.List.get(index).getMaXuLy());
            cbxMaP.setSelectedItem(ListMaP.get(index));
            txtTienPhat_XLQH.setText(XuLyQuanHanController.List.get(index).getTienPhat() + "");
            cbxLyDo_XLQH.setSelectedItem(XuLyQuanHanController.List.get(index).getLyDo());
            cbxTrangThai_QLQH.setSelectedItem(XuLyQuanHanController.List.get(index).getTrangThai());

        }
    }//GEN-LAST:event_tblQuaHan_QLQHMouseClicked

    private void cbxLyDo_XLQHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLyDo_XLQHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLyDo_XLQHActionPerformed

    private void txtHoVaTen_QLMTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoVaTen_QLMTFocusGained


    }//GEN-LAST:event_txtHoVaTen_QLMTFocusGained

    private void txtMaSinhVien_QLMTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaSinhVien_QLMTFocusLost
       try {
            txtHoVaTen_QLMT.setText(PhieuController.LayTenBD(txtMaSinhVien_QLMT.getText()));
        } catch (Exception ex) {
            Logger.getLogger(NhanVienQLMuonTraForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMaSinhVien_QLMTFocusLost
    public void ThemPhieu(Phieu tl) throws BadLocationException, ParseException {
        tl.setMaBanDoc(txtMaSinhVien_QLMT.getText());
        tl.setMaPhieu(txtMaPhieu_QLMT.getText());
        tl.setMaTaiLieu(cbxMaTL_NVQLMT.getSelectedItem().toString());
        tl.setHoVaTen(txtHoVaTen_QLMT.getText());
        tl.setNgayMuon(new SimpleDateFormat("yyyy-MM-dd").parse(txtNgayMuon_QLMT.getText()));
        tl.setNgayThucTra(new SimpleDateFormat("yyyy-MM-dd").parse(txtNgayThucTra_QLMT.getText()));
        tl.setNgayTra(new SimpleDateFormat("yyyy-MM-dd").parse(txtNgayTra_QLMT.getText()));

    }

    public void HienThiPhieu(ArrayList<Phieu> Listx) {
        modelPhieu.setRowCount(0);
        Listx.forEach((x) -> {
            modelPhieu.addRow(new Object[]{
                x.getMaPhieu(), x.getMaTaiLieu(), x.getMaBanDoc(), x.getHoVaTen(), x.getNgayMuon(), x.getNgayTra(), x.getNgayThucTra()
            });
        });
    }

    public void HienThiPhieu1(ArrayList<Phieu> Listx) {
        TimKiem.setRowCount(0);
        Listx.forEach((x) -> {
            TimKiem.addRow(new Object[]{
                x.getMaPhieu(), x.getMaTaiLieu(), x.getMaBanDoc(), x.getHoVaTen(), x.getNgayMuon(), x.getNgayTra(), x.getNgayThucTra()
            });
        });
    }

    public void HienThiXuLy(ArrayList<XuLyQuaHan> Listx) {
        modelXuLy.setRowCount(0);
        Listx.forEach((x) -> {
            modelXuLy.addRow(new Object[]{
                x.getMaXuLy(), x.getMaPhieuMuon(), x.getLyDo(), x.getTienPhat(), x.getTrangThai()
            });
            ListMaP.add(x.getMaPhieuMuon());
        });
    }
    public void HienThiXuLy1(ArrayList<XuLyQuaHan> Listx) {
        TimKiem.setRowCount(0);
        Listx.forEach((x) -> {
            TimKiem.addRow(new Object[]{
                x.getMaXuLy(),x.getMaPhieuMuon(), x.getLyDo() , x.getTienPhat() , x.getTrangThai()
            });
            ListMaP.add(x.getMaPhieuMuon());
        });
    }
    public void HienThiBanDoc1(ArrayList<BanDoc> Listx) {
        TimKiem.setRowCount(0);
        Listx.forEach((x) -> {
            TimKiem.addRow(new Object[]{
                x.getMaBanDoc(), x.getTenBanDoc(), x.getNgaySinh(), x.getKhoa(), "+840" + x.getSoDienThoai(), x.getGioiTinh()
            });
        });
    }

    public void SuaPhieu() throws SQLException, Exception {
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn sửa ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            int index = tblQuanLyMuonTra.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng để sửa");
            } else {
                Phieu tl = new Phieu();
                ThemPhieu(tl);
                PhieuController.SuaPhieu(tl);

            }
            PhieuController.HienThi();
            HienThiPhieu(PhieuController.List);
        }
    }

    public void XoaPhieu() throws SQLException, Exception {
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            int index = tblQuanLyMuonTra.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng để xóa");
            } else {
                PhieuController.XoaPhieu(txtMaPhieu_QLMT.getText());
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                PhieuController.HienThi();
                HienThiPhieu(PhieuController.List);
            }

        }

    }

    
    public static ArrayList<String> ListMaP = new ArrayList<>();

    public void ThemXuLy(XuLyQuaHan tl) throws BadLocationException, ParseException {
        tl.setMaXuLy(txtMaXuLy_XLQH.getText());
        tl.setMaPhieuMuon(cbxMaP.getSelectedItem().toString());
        tl.setTienPhat(Double.parseDouble(txtTienPhat_XLQH.getText()));
        tl.setLyDo(cbxLyDo_XLQH.getSelectedItem().toString());
        tl.setTrangThai(cbxTrangThai_QLQH.getSelectedItem().toString());
        ListMaP.add(cbxMaP.getSelectedItem().toString());
    }

    public void SuaXuLy() throws SQLException, Exception {
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn sửa ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            int index = tblQuaHan_QLQH.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn phiếu để sửa");
            } else {
                XuLyQuaHan tl = new XuLyQuaHan();
                ThemXuLy(tl);
                XuLyQuanHanController.SuaXuLy(tl);

            }
            XuLyQuanHanController.HienThi();
            HienThiXuLy(XuLyQuanHanController.List);
        }
    }

    public void Load() throws Exception {

        XuLyQuanHanController.HienThi();
        HienThiXuLy(XuLyQuanHanController.List);
        PhieuController.HienThi();
        HienThiPhieu(PhieuController.List);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienQLMuonTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienQLMuonTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienQLMuonTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienQLMuonTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NhanVienQLMuonTraForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(NhanVienQLMuonTraForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat3;
    private javax.swing.JButton btnDangXuat4;
    private javax.swing.JButton btnHienThiPhieuMuon;
    private javax.swing.JButton btnHienThiPhieuXL;
    private javax.swing.JButton btnLapPhieuMuon;
    private javax.swing.JButton btnQuaHan;
    private javax.swing.JButton btnSuaPhieuMuon;
    private javax.swing.JButton btnSuaPhieuXL;
    private javax.swing.JButton btnThemPhieuXL;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoaPhieuMuon;
    private javax.swing.JComboBox<String> cbxDoiTuong;
    private javax.swing.JComboBox<String> cbxLyDo_XLQH;
    private javax.swing.JComboBox<String> cbxMaP;
    private javax.swing.JComboBox<String> cbxMaTL_NVQLMT;
    private javax.swing.JComboBox<String> cbxThuocTinh;
    private javax.swing.JComboBox<String> cbxTrangThai_QLQH;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelQuanLyBanDoc;
    private javax.swing.JPanel jPanelQuanLyPhieuMuon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblQuaHan_QLQH;
    private javax.swing.JTable tblQuanLyMuonTra;
    private javax.swing.JTable tbl_TimKiem;
    private javax.swing.JTextField txtHoVaTen_QLMT;
    private javax.swing.JTextField txtMaPhieu_QLMT;
    private javax.swing.JTextField txtMaSinhVien_QLMT;
    private javax.swing.JTextField txtMaXuLy_XLQH;
    private javax.swing.JTextField txtNgayMuon_QLMT;
    private javax.swing.JTextField txtNgayThucTra_QLMT;
    private javax.swing.JTextField txtNgayTra_QLMT;
    private javax.swing.JTextField txtTienPhat_XLQH;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
