/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.BanDocController;
import static DAO.BanDocController.ThemBanDoc;

import DAO.NhanVienController;
import DAO.PhieuController;
import DAO.TaiLieuController;
import DTO.BanDoc;

import DTO.TaiLieu;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class NhanVienQLTaiLieuForm extends javax.swing.JFrame {

    /**
     * Creates new form NhanVien1
     */
    DefaultTableModel modelTaiLieu;
    DefaultTableModel modelBanDoc;
    DefaultTableModel TimKiem;

    public NhanVienQLTaiLieuForm() throws Exception {
        this.setTitle("Quản lý tài liệu");
        initComponents();
        modelTaiLieu = (DefaultTableModel) tblQuanLyTaiLieu.getModel();
        modelBanDoc = (DefaultTableModel) tblQuanlydocgia.getModel();
        TimKiem = (DefaultTableModel) tbl_TimKiem.getModel();
        HTcbx();
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanelQuanLyTaiLieu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaTaiLieu_QLTL = new javax.swing.JTextField();
        txtTenTaiLieu_QLTL = new javax.swing.JTextField();
        txtTacGia_QLTL = new javax.swing.JTextField();
        txtSoLuongCo_QLTL = new javax.swing.JTextField();
        txtNamXuatBan_QLTL = new javax.swing.JTextField();
        txtGiaSach_QLTL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnThemTaiLieu = new javax.swing.JButton();
        btnSuaTaiLieu = new javax.swing.JButton();
        btnXoaTaiLieu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanLyTaiLieu = new javax.swing.JTable();
        btnDangXuat = new javax.swing.JButton();
        btnHienThiTaiLieu = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        cbxNhaXuatBan = new javax.swing.JComboBox();
        cbxTheLoai = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbxViTri = new javax.swing.JComboBox();
        jPanelQuanLyBanTaiLieu = new javax.swing.JPanel();
        jPanelQuanLyBanTaiLieu1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtKhoa = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMadocgia = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtTenDG = new javax.swing.JTextField();
        Khoa = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtGioitinh = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblQuanlydocgia = new javax.swing.JTable();
        btnThemBanDoc = new javax.swing.JButton();
        btnDangXuat2 = new javax.swing.JButton();
        HienThiHoaDon = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        cbxDoiTuong = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        cbxThuocTinh = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_TimKiem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel1.setText("Mã tài liệu");

        jLabel2.setText("Tên tài liệu");

        jLabel3.setText("Nhà xuất bản");

        jLabel4.setText("Tác giả");

        jLabel5.setText("Số lượng có");

        jLabel6.setText("Thể loại");

        jLabel7.setText("Năm xuất bản");

        jLabel8.setText("Giá sách");

        btnThemTaiLieu.setBackground(new java.awt.Color(0, 153, 102));
        btnThemTaiLieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemTaiLieu.setForeground(new java.awt.Color(255, 255, 255));
        btnThemTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132335_add_icon.png"))); // NOI18N
        btnThemTaiLieu.setText("Thêm tài liệu");
        btnThemTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTaiLieuActionPerformed(evt);
            }
        });

        btnSuaTaiLieu.setBackground(new java.awt.Color(0, 153, 102));
        btnSuaTaiLieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaTaiLieu.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132187_refresh_icon.png"))); // NOI18N
        btnSuaTaiLieu.setText("Sửa tài liệu");
        btnSuaTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTaiLieuActionPerformed(evt);
            }
        });

        btnXoaTaiLieu.setBackground(new java.awt.Color(0, 153, 102));
        btnXoaTaiLieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaTaiLieu.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132192_delete_icon.png"))); // NOI18N
        btnXoaTaiLieu.setText("Xóa tài liệu");
        btnXoaTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiLieuActionPerformed(evt);
            }
        });

        tblQuanLyTaiLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài liệu", "Tên tài liệu", "Nhà xuất bản", "Tác giả", "Số lượng có", "Thể loại", "Năm xuất bản", "Giá sách", "Vi tri"
            }
        ));
        tblQuanLyTaiLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyTaiLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanLyTaiLieu);

        btnDangXuat.setBackground(new java.awt.Color(0, 153, 102));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/171495_right_exit_icon (1).png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnHienThiTaiLieu.setBackground(new java.awt.Color(0, 153, 102));
        btnHienThiTaiLieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHienThiTaiLieu.setForeground(new java.awt.Color(255, 255, 255));
        btnHienThiTaiLieu.setText("Hiển thị");
        btnHienThiTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiTaiLieuActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 0, 255));
        jLabel39.setText(" Danh sách tài liệu ");

        jLabel9.setText("Vi tri");

        cbxViTri.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Khu A", "Khu B", "Khu C", "Khu D" }));
        cbxViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxViTriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelQuanLyTaiLieuLayout = new javax.swing.GroupLayout(jpanelQuanLyTaiLieu);
        jpanelQuanLyTaiLieu.setLayout(jpanelQuanLyTaiLieuLayout);
        jpanelQuanLyTaiLieuLayout.setHorizontalGroup(
            jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                        .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addComponent(jLabel39))
                            .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                                        .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                                                .addGap(108, 108, 108)
                                                .addComponent(btnSuaTaiLieu)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnXoaTaiLieu))
                                            .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtMaTaiLieu_QLTL)
                                                    .addComponent(txtTenTaiLieu_QLTL, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                                    .addComponent(txtTacGia_QLTL, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                                    .addComponent(cbxNhaXuatBan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addComponent(btnThemTaiLieu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHienThiTaiLieu)
                                .addGap(375, 375, 375)))
                        .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btnDangXuat)
                                .addGap(0, 18, Short.MAX_VALUE))
                            .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNamXuatBan_QLTL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                        .addComponent(txtSoLuongCo_QLTL)
                                        .addComponent(txtGiaSach_QLTL, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(cbxViTri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jpanelQuanLyTaiLieuLayout.setVerticalGroup(
            jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaTaiLieu_QLTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoLuongCo_QLTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenTaiLieu_QLTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(cbxTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamXuatBan_QLTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTacGia_QLTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtGiaSach_QLTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                        .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThemTaiLieu)
                                    .addComponent(btnSuaTaiLieu)))
                            .addGroup(jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cbxViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelQuanLyTaiLieuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaTaiLieu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHienThiTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanelQuanLyTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangXuat)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý tài liệu", jpanelQuanLyTaiLieu);

        jPanelQuanLyBanTaiLieu1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel22.setText("Họ và tên");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel23.setText("Mã độc giả");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel24.setText("Ngày sinh");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel25.setText("Giới tính");

        Khoa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Khoa.setText("Khoa");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setText("Số điện thoại");

        tblQuanlydocgia.setBackground(new java.awt.Color(245, 245, 245));
        tblQuanlydocgia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblQuanlydocgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã độc giả", "Họ tên", "Ngày sinh", "Khoa", "Số điện thoại", "Giới tính"
            }
        ));
        tblQuanlydocgia.setGridColor(new java.awt.Color(0, 0, 0));
        tblQuanlydocgia.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblQuanlydocgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanlydocgiaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblQuanlydocgia);

        btnThemBanDoc.setBackground(new java.awt.Color(0, 153, 102));
        btnThemBanDoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemBanDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnThemBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132335_add_icon.png"))); // NOI18N
        btnThemBanDoc.setText("Thêm bạn đọc");
        btnThemBanDoc.setToolTipText("Thêm hóa đơn");
        btnThemBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBanDocActionPerformed(evt);
            }
        });

        btnDangXuat2.setBackground(new java.awt.Color(0, 153, 102));
        btnDangXuat2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangXuat2.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/171495_right_exit_icon (1).png"))); // NOI18N
        btnDangXuat2.setText("Đăng Xuất");
        btnDangXuat2.setToolTipText("Đăng Xuất");
        btnDangXuat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuat2ActionPerformed(evt);
            }
        });

        HienThiHoaDon.setBackground(new java.awt.Color(0, 153, 102));
        HienThiHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HienThiHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        HienThiHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/3671905_show_view_icon.png"))); // NOI18N
        HienThiHoaDon.setText("Hiển thị");
        HienThiHoaDon.setToolTipText("Hiển thị");
        HienThiHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HienThiHoaDonActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 153, 102));
        jLabel37.setText("Danh sách độc giả");

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/132187_refresh_icon.png"))); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQuanLyBanTaiLieu1Layout = new javax.swing.GroupLayout(jPanelQuanLyBanTaiLieu1);
        jPanelQuanLyBanTaiLieu1.setLayout(jPanelQuanLyBanTaiLieu1Layout);
        jPanelQuanLyBanTaiLieu1Layout.setHorizontalGroup(
            jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyBanTaiLieu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuanLyBanTaiLieu1Layout.createSequentialGroup()
                        .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelQuanLyBanTaiLieu1Layout.createSequentialGroup()
                                .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24))
                                .addGap(45, 45, 45)
                                .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMadocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelQuanLyBanTaiLieu1Layout.createSequentialGroup()
                                .addComponent(btnThemBanDoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HienThiHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQuanLyBanTaiLieu1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel37))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                        .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuanLyBanTaiLieu1Layout.createSequentialGroup()
                                .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25)
                                    .addComponent(Khoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKhoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGioitinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnDangXuat2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelQuanLyBanTaiLieu1Layout.setVerticalGroup(
            jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyBanTaiLieu1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtMadocgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Khoa)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel27)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(txtGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuanLyBanTaiLieu1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanelQuanLyBanTaiLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemBanDoc)
                            .addComponent(HienThiHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel37))
                    .addGroup(jPanelQuanLyBanTaiLieu1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnDangXuat2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout jPanelQuanLyBanTaiLieuLayout = new javax.swing.GroupLayout(jPanelQuanLyBanTaiLieu);
        jPanelQuanLyBanTaiLieu.setLayout(jPanelQuanLyBanTaiLieuLayout);
        jPanelQuanLyBanTaiLieuLayout.setHorizontalGroup(
            jPanelQuanLyBanTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
            .addGroup(jPanelQuanLyBanTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQuanLyBanTaiLieuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelQuanLyBanTaiLieu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelQuanLyBanTaiLieuLayout.setVerticalGroup(
            jPanelQuanLyBanTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
            .addGroup(jPanelQuanLyBanTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQuanLyBanTaiLieuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelQuanLyBanTaiLieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Quản lý bạn đọc", jPanelQuanLyBanTaiLieu);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel41.setText("Nhập thông tin cần tìm");

        txtTimKiem.setText("Search");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
        });
        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimKiemMouseClicked(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        cbxDoiTuong.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbxDoiTuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đơn Hàng", "Tài Liệu", "Bạn đọc" }));
        cbxDoiTuong.setToolTipText("Chọn loại nhân viên ");
        cbxDoiTuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDoiTuongActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel42.setText("Chọn đối tượng cần tìm");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel43.setText("Chọn thuộc tính để tìm");

        cbxThuocTinh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbxThuocTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã đơn hàng", "Họ và tên", "Mã tài liệu" }));
        cbxThuocTinh.setToolTipText("Chọn kiểu tìm kiếm");

        btnTimKiem.setBackground(new java.awt.Color(51, 0, 255));
        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm ");
        btnTimKiem.setToolTipText("Tìm kiếm hóa đơn");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tbl_TimKiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tbl_TimKiem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTimKiem)
                            .addComponent(cbxDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel43)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel43)
                    .addComponent(cbxThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(btnTimKiem))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tìm kiếm", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void HTcbx() {
        try {
            TaiLieuController.LayTenTheLoai();
            TaiLieuController.LayTenNhaXuatBan();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String s : TaiLieuController.ListNhaXuatBan) {
            cbxNhaXuatBan.addItem(s);
        }
        for (String s : TaiLieuController.ListTheLoai) {
            cbxTheLoai.addItem(s);
        }

    }


    private void btnThemTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTaiLieuActionPerformed
        if (txtMaTaiLieu_QLTL.getText().trim().equals("")
                || txtTenTaiLieu_QLTL.getText().trim().equals("")
                || txtTacGia_QLTL.getText().trim().equals("")
                || txtSoLuongCo_QLTL.getText().trim().equals("")
                || txtGiaSach_QLTL.getText().trim().equals("")
                || txtNamXuatBan_QLTL.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin");
        } else {

            TaiLieu tl = new TaiLieu();
            ThemTaiLieu(tl);
            try {
                if (!TaiLieuController.Check(txtMaTaiLieu_QLTL.getText())) {
                    try {
                        TaiLieuController.ThemTaiLieu(tl);

                    } catch (SQLException ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        Load();
                    } catch (Exception ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Đã tồn tại mã tài liệu này");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnThemTaiLieuActionPerformed

    private void btnSuaTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTaiLieuActionPerformed
        if (txtMaTaiLieu_QLTL.getText().trim().equals("")
                || txtTenTaiLieu_QLTL.getText().trim().equals("")
                || txtTacGia_QLTL.getText().trim().equals("")
                || txtSoLuongCo_QLTL.getText().trim().equals("")
                || txtGiaSach_QLTL.getText().trim().equals("")
                || txtNamXuatBan_QLTL.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin");
        } else {
            try {
                SuaTaiLieu();
            } catch (Exception ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSuaTaiLieuActionPerformed

    private void btnXoaTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiLieuActionPerformed
        try {
            XoaTaiLieu();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaTaiLieuActionPerformed

    private void tblQuanLyTaiLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyTaiLieuMouseClicked
        int index = tblQuanLyTaiLieu.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng");
        } else {
            txtMaTaiLieu_QLTL.setText(TaiLieuController.List.get(index).getMaTaiLieu());
            txtTenTaiLieu_QLTL.setText(TaiLieuController.List.get(index).getTenTaiLieu());

            txtTacGia_QLTL.setText(TaiLieuController.List.get(index).getTenTacGia());
            txtSoLuongCo_QLTL.setText(TaiLieuController.List.get(index).getSoLuongCo() + "");

            txtNamXuatBan_QLTL.setText(TaiLieuController.List.get(index).getNamXuatBan() + "");
            txtGiaSach_QLTL.setText(TaiLieuController.List.get(index).getGiaSach() + "");

            cbxNhaXuatBan.setSelectedItem(TaiLieuController.List.get(index).getNhaXuatBan());
            cbxTheLoai.setSelectedItem(TaiLieuController.List.get(index).getTheLoai());
            cbxViTri.setSelectedItem(TaiLieuController.List.get(index).getViTri());

        }


    }//GEN-LAST:event_tblQuanLyTaiLieuMouseClicked

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn đăng xuất ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            HomePage x = new HomePage();
            x.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnHienThiTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiTaiLieuActionPerformed
        try {
            TaiLieuController.HienThi();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);

        }
        HienThiTaiLieu(TaiLieuController.List);
    }//GEN-LAST:event_btnHienThiTaiLieuActionPerformed

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemMouseClicked

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed
    public void HienThiBanDoc1(ArrayList<BanDoc> Listx) {
        TimKiem.setRowCount(0);
        Listx.forEach((x) -> {
            TimKiem.addRow(new Object[]{
                x.getMaBanDoc(), x.getTenBanDoc(), x.getNgaySinh(), x.getKhoa(), "0" + x.getSoDienThoai(), x.getGioiTinh()
            });
        });
    }
    private void cbxDoiTuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDoiTuongActionPerformed
        switch (cbxDoiTuong.getSelectedItem().toString()) {
            case "Đơn Hàng":
                cbxThuocTinh.removeAllItems();
                cbxThuocTinh.addItem("Mã đơn hàng");
                cbxThuocTinh.addItem("Họ và tên");
                cbxThuocTinh.addItem("Mã tài liệu");
                break;
            case "Tài Liệu":
                cbxThuocTinh.removeAllItems();
                cbxThuocTinh.addItem("Mã tài liệu");
                cbxThuocTinh.addItem("Tên tài liệu");
                cbxThuocTinh.addItem("Thể loại");
                cbxThuocTinh.addItem("Tác giả");
                cbxThuocTinh.addItem("Nhà xuất bản");
                break;
            case "Bạn đọc":
                cbxThuocTinh.removeAllItems();
                cbxThuocTinh.addItem("Mã bạn đọc");
                cbxThuocTinh.addItem("Tên bạn đọc");
                break;
            default:
                break;

        }
    }//GEN-LAST:event_cbxDoiTuongActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        switch (cbxDoiTuong.getSelectedItem().toString()) {
            case "Đơn Hàng":
                TimKiem.setColumnIdentifiers(new Object[]{
                    "Mã đơn hàng", "Mã tài liệu", "Họ và tên", "Số điện thoại", "Số lượng", "Giá tiền"
                });
                switch (cbxThuocTinh.getSelectedItem().toString()) {
                   
                   
            case "Tài Liệu":
                TimKiem.setColumnIdentifiers(new Object[]{
                    "Mã tài liệu", "Tên tài liệu", "Nhà xuất bản", "Tác giả", "Số lượng có", "Thể loại", "Năm xuất bản", "Giá sách"
                });
                switch (cbxThuocTinh.getSelectedItem().toString()) {
                    case "Mã tài liệu":
                        try {
                            TaiLieuController.TimKiemMaTL(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;

                    case "Tên tài liệu":
                        try {
                            TaiLieuController.TimKiemTenTL(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;
                    case "Tác giả":
                        try {
                            TaiLieuController.TimKiemTacGia(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;

                    default:
                        break;
                }

                HienThiTaiLieu1(TaiLieuController.List1);
                break;

            case "Bạn đọc":

                TimKiem.setColumnIdentifiers(new Object[]{
                    "Mã bạn đọc", "Tên bạn đọc", "Ngày sinh", "Lớp - Khóa", "Số điện thoại", "Giới tính"
                });
                switch (cbxThuocTinh.getSelectedItem().toString()) {
                    case "Mã bạn đọc":
                        try {
                            BanDocController.TimKiemMaSV(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;
                    case "Tên bạn đọc":
                        try {
                            BanDocController.TimKiemTenSV(txtTimKiem.getText());
                        } catch (Exception ex) {
                            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;

                    default:
                        break;
                }

                HienThiBanDoc1(BanDocController.List1);
                break;

            default:
                break;
                
                }
                }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void cbxViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxViTriActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_cbxViTriActionPerformed

    private void tblQuanlydocgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanlydocgiaMouseClicked
        int index = tblQuanlydocgia.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng");
        } else {
            txtMadocgia.setText(BanDocController.List.get(index).getMaBanDoc());
            txtTenDG.setText(BanDocController.List.get(index).getTenBanDoc());
            txtNgaySinh.setText(BanDocController.List.get(index).getNgaySinh() + "");
            txtKhoa.setText(BanDocController.List.get(index).getKhoa());
            txtSdt.setText(BanDocController.List.get(index).getSoDienThoai()+ "");
            txtGioitinh.setText(BanDocController.List.get(index).getGioiTinh());

        }
    }//GEN-LAST:event_tblQuanlydocgiaMouseClicked

    private void btnThemBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBanDocActionPerformed
        if (txtMadocgia.getText().trim().equals("")
            || txtTenDG.getText().trim().equals("")
            || txtNgaySinh.getText().trim().equals("")
            || txtKhoa.getText().trim().equals("")
            || txtSdt.getText().trim().equals("")
            || txtGioitinh.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin");
        } else {

            BanDoc tl = new BanDoc();
            try {
                ThemBanDoc(tl);
            } catch (ParseException ex) {
                Logger.getLogger(NhanVienQLTaiLieuForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if (!BanDocController.Check(txtMadocgia.getText())) {
                    try {
                        BanDocController.ThemBanDoc(tl);

                    } catch (SQLException ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        Load();
                    } catch (Exception ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Đã tồn tại mã doc gia nay");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemBanDocActionPerformed
public void ThemBanDoc(BanDoc tl) throws ParseException {
       tl.setMaBanDoc(txtMadocgia.getText());
        tl.setSoDienThoai(Integer.parseInt(txtSdt.getText()));
        tl.setTenBanDoc(txtTenDG.getText());
        tl.setKhoa(txtKhoa.getText());
        tl.setGioiTinh(txtGioitinh.getText());
        tl.setNgaySinh(new SimpleDateFormat("yyyy-MM-dd").parse(txtNgaySinh.getText()));
    }
    private void btnDangXuat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuat2ActionPerformed
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn đăng xuất ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            HomePage x = new HomePage();
            x.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnDangXuat2ActionPerformed

    private void HienThiHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HienThiHoaDonActionPerformed
        try {
            BanDocController.HienThi();
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);

        }
        HienThiBanDoc(BanDocController.List);
    }//GEN-LAST:event_HienThiHoaDonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtMadocgia.getText().trim().equals("")
            || txtKhoa.getText().trim().equals("")
            || txtTenDG.getText().trim().equals("")
            || txtSdt.getText().trim().equals("")
            || txtNgaySinh.getText().trim().equals("")
            || txtGioitinh.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin");
        } else {
            try {
                SuaBanDoc();
            } catch (Exception ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public void Load() throws Exception {
        TaiLieuController.HienThi();
        HienThiTaiLieu(TaiLieuController.List);
         BanDocController.HienThi();
         HienThiBanDoc(BanDocController.List);
        
    }

    
    

    public void HienThiHoaDon1(ArrayList<BanDoc> Listx) {
        TimKiem.setRowCount(0);
        Listx.forEach((x) -> {
            TimKiem.addRow(new Object[]{
            
            });
        });
    }

    

    public void HienThiTaiLieu(ArrayList<TaiLieu> Listx) {
        modelTaiLieu.setRowCount(0);
        Listx.forEach((x) -> {
            modelTaiLieu.addRow(new Object[]{
                x.getMaTaiLieu(), x.getTenTaiLieu(), x.getNhaXuatBan(), x.getTenTacGia(), x.getSoLuongCo(), x.getTheLoai(), x.getNamXuatBan(), x.getGiaSach(), x.getViTri()
            });
            ListNXB.add(x.getNhaXuatBan());
            ListTheLoai.add(x.getTheLoai());
        });
    }

    public void HienThiTaiLieu1(ArrayList<TaiLieu> Listx) {
        TimKiem.setRowCount(0);
        Listx.forEach((x) -> {
            TimKiem.addRow(new Object[]{
                x.getMaTaiLieu(), x.getTenTaiLieu(), x.getNhaXuatBan(), x.getTenTacGia(), x.getSoLuongCo(), x.getTheLoai(), x.getNamXuatBan(), x.getGiaSach(), x.getViTri()
            });
        });
    }

    public void SuaTaiLieu() throws SQLException, Exception {
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn sửa ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            int index = tblQuanLyTaiLieu.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng để sửa");
            } else {
                TaiLieu tl = new TaiLieu();
                ThemTaiLieu(tl);
                TaiLieuController.SuaTaiLieu(tl);

            }
            TaiLieuController.HienThi();
            HienThiTaiLieu(TaiLieuController.List);
        }
    }

    public void SuaHoaDon() throws SQLException, Exception {
        
    }
    public static ArrayList<String> ListNXB = new ArrayList<>();
    public static ArrayList<String> ListTheLoai = new ArrayList<>();

    public void ThemTaiLieu(TaiLieu tl) {
        tl.setGiaSach(Float.parseFloat(txtGiaSach_QLTL.getText()));
        tl.setMaTaiLieu(txtMaTaiLieu_QLTL.getText());
        tl.setNamXuatBan(Integer.parseInt(txtNamXuatBan_QLTL.getText()));

        tl.setSoLuongCo(Integer.parseInt(txtSoLuongCo_QLTL.getText()));
        tl.setTacGia(txtTacGia_QLTL.getText());
        tl.setTenTaiLieu(txtTenTaiLieu_QLTL.getText());

        tl.setNhaXuatBan(cbxNhaXuatBan.getSelectedItem().toString());
        tl.setTheLoai(cbxTheLoai.getSelectedItem().toString());
        tl.setViTri(cbxViTri.getSelectedItem().toString());

        ListNXB.add(cbxNhaXuatBan.getSelectedItem().toString());
        ListTheLoai.add(cbxTheLoai.getSelectedItem().toString());

    }

    public void XoaTaiLieu() throws SQLException, Exception {
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            int index = tblQuanLyTaiLieu.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng để xóa");
            } else {
                TaiLieuController.XoaTaiLieu(txtMaTaiLieu_QLTL.getText());
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                TaiLieuController.HienThi();
                HienThiTaiLieu(TaiLieuController.List);
            }
        }

    }
public void SuaBanDoc() throws SQLException, Exception {
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn sửa ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            int index = tblQuanlydocgia.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn hàng để sửa");
            } else {
                BanDoc tl = new BanDoc();
                ThemBanDoc(tl);
                BanDocController.SuaBanDoc(tl);

            }
            BanDocController.HienThi();
            HienThiBanDoc(BanDocController.List);
        }
    }
public void HienThiBanDoc(ArrayList<BanDoc> Listx) {
        modelBanDoc.setRowCount(0);
        Listx.forEach((x) -> {
            modelBanDoc.addRow(new Object[]{
                x.getMaBanDoc(), x.getTenBanDoc(), x.getNgaySinh(), x.getKhoa(), "0" + x.getSoDienThoai(), x.getGioiTinh()
            });
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienQLTaiLieuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienQLTaiLieuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienQLTaiLieuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienQLTaiLieuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NhanVienQLTaiLieuForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(NhanVienQLTaiLieuForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HienThiHoaDon;
    private javax.swing.JLabel Khoa;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDangXuat2;
    private javax.swing.JButton btnHienThiTaiLieu;
    private javax.swing.JButton btnSuaTaiLieu;
    private javax.swing.JButton btnThemBanDoc;
    private javax.swing.JButton btnThemTaiLieu;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoaTaiLieu;
    private javax.swing.JComboBox<String> cbxDoiTuong;
    private javax.swing.JComboBox cbxNhaXuatBan;
    private javax.swing.JComboBox cbxTheLoai;
    private javax.swing.JComboBox<String> cbxThuocTinh;
    private javax.swing.JComboBox cbxViTri;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelQuanLyBanTaiLieu;
    private javax.swing.JPanel jPanelQuanLyBanTaiLieu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpanelQuanLyTaiLieu;
    private javax.swing.JTable tblQuanLyTaiLieu;
    private javax.swing.JTable tblQuanlydocgia;
    private javax.swing.JTable tbl_TimKiem;
    private javax.swing.JTextField txtGiaSach_QLTL;
    private javax.swing.JTextField txtGioitinh;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtMaTaiLieu_QLTL;
    private javax.swing.JTextField txtMadocgia;
    private javax.swing.JTextField txtNamXuatBan_QLTL;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSoLuongCo_QLTL;
    private javax.swing.JTextField txtTacGia_QLTL;
    private javax.swing.JTextField txtTenDG;
    private javax.swing.JTextField txtTenTaiLieu_QLTL;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
